; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino

[env:esp32pid]
board = esp32-c3-devkitm-1
build_src_filter = +<esp_pid.cpp> +<motor_cmd.h> +<motor_cmd.cpp> -<esp_cam.cpp> -<app_httpd.cpp> -<camera_pins.h> -<camera_index.h>
build_flags = -Wno-deprecated-declarations
lib_deps = 
    madhephaestus/ESP32Servo

[env:esp32cam]
board = esp32cam
build_src_filter = +<esp_cam.cpp> +<app_httpd.cpp> +<camera_pins.h> +<camera_index.h> -<motor_cmd.h> -<motor_cmd.cpp> -<esp_pid.cpp>